### ISSUE TITLE
encoding problem for Purdue (convert to utf8 script)

### ISSUE THREAD

**Issue by Gee-CityU** [writecrow/text_processing#12]
files are identified as utf8, but remain the binary format.
[1_A_CHN_1_F_10184.txt](https://github.com/writecrow/text_processing/files/1763975/1_A_CHN_1_F_10184.txt)

we tried the python script but end up in ascii format but in different purpose:
[utf8conv.txt](https://github.com/writecrow/text_processing/files/1763987/utf8conv.txt)

**Comment by picoral** [comment]
ascii is utf8

**Comment by Gee-CityU** [comment]
Hi @picoral, thanks clarification. 
The real problem is that by running the utf8conv script & the script you wrote (normalization.py), we still have binary encoding in Purdue files when I use "file -i *.txt" to check it. You recommended me another script to run (python cp1251_to_utf8.py *.txt) last winter, but it doesn't fix the binary problem for some reason.... I reported the problem with Mark and hopefully we all will figure this out together.

**Comment by markfullmer** [comment]
Additional context: on my flight home from Purdue, I did some modified text normalization on the file that @gelan890926 sent along and was able to strip out a character that was problematic; at that point, running a `file --mime-encoding` made the system interpret the file as being in `us-ascii`, rather than `binary`.

Another way of saying that is that when the system says the file is `binary`, I think, it really just means that it can't reliably determine an encoding format for the file, based on the bytes in the file.  When I removed the problematic character, it then said, "Oh, I can recognize all these bytes, and they conform to `us-ascii` encoding."

This is the underlying issue with any encoding script: if it can't reliably determine the original encoding, it won't know how to decode it, before re-encoding it in `utf-8`. I'll report more when I have a chance, on what would be the "right" way to handle this...

The file that @gelan890926 posted at the top of this issue illustrates the problem, if you'd like to give it a try on your end @picoral

**Comment by Gee-CityU** [comment]
Thanks, @markfullmer. Would you mind sharing the modified script (like the one that strips out the first and/or second character) here? In this way, I can also use it to test the Purdue data, and used it as a sample when I get other problematic characters. 

I had some ideas of doing this: for example, when print the text, print from the second/third character like:
x="近軑<ID: 10224>"
y=x[2:]
print(y)

But I'm not sure if this works the best with your script, so it will be great if i can see your solution on this problem. Thank you very much!
(We are in spring break so I'm a little late to reply your post, sorry...)
