### ISSUE TITLE
Text Processing Issue #2

### ISSUE THREAD

**Issue by gao339** [writecrow/text_processing#14]
test-data/for-cleaning.txt      <type 'exceptions.UnicodeDecodeError'>  'ascii' codec can't decode byte 0xe2 in position 18: ordinal not in range(128)

**Comment by markfullmer** [comment]
@abushner quickly diagnosed this issue as the script was being run with Python 2, rather than Python 3 (the command did not produce this error when run explicitly with `python3`). 

The recommended solution for others having this issue is to add an alias to your `~/.bash_profile` file as shown below:

`alias python="/usr/local/bin/python3"`

This alias will allow you to run the python3 executable when you type `python`. (You'll need either to quit & restart your terminal, or run `source ~/.bash_profile` for the alias to take effect.

Marking this as closed.

**Comment by cbdilger** [comment]
.@markfullmer, we may need to add "WTF is ~/.bash_profile" to a doc somewhere...
